### ISSUE TITLE
Material Checkbox and TreeView tick and dash are vertically below centre

### ISSUE THREAD

**Issue by buzzware** [unoplatform/Uno.Themes#1234]
## Current behavior

See https://gallery.platform.uno for Checkbox & TreeView in Material Theme

<img width="314" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/28285/1144e801-da7c-4a9b-a3b5-b5ef6e307dc6">

<img width="764" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/28285/dee1b9f7-71b9-46a7-8481-8d564f1fa6f5">

## Expected behavior

<img width="476" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/28285/0287c68b-dfb0-4635-a59c-a011f1ee09e8">

**Comment by Youssef1313** [comment]
I think https://github.com/unoplatform/Uno.Themes/pull/1202 should fix it.

**Comment by kazo0** [comment]
Thanks for the report @buzzware , good catch!

#1202 just merged so we will validate it with the resulting build to see if that fixes the issue in Material and it should go out with the next update of [Gallery](https://github.com/unoplatform/Uno.Gallery)

**Comment by Soap-141** [comment]
Hello, any update on this?

**Comment by Soap-141** [comment]
On Android I'm still having the issue, see  WinUI vs Android.

![Image](https://github.com/user-attachments/assets/5b09f215-0e1e-4723-9823-555b6dc6999d)

CC: @kazo0 @Youssef1313
